/**
 * Base class for instruments. All instruments should extend this class and implement the init(), play(), and tearDown() methods.
 * See API/Builtin/VstInstrument.js for an example implementation.
 */
export class InstrumentBase {
    DEFAULT_INSTRUMENT_NAME = "instrumentbase-302571";
    /**
     * Declare any properties here (but no resource-heavy stuff here)
     */
    constructor() {
        this.hasUI = false; // Set this to true, and the container InnerHTML will not be overwritten with "No settings available for this instrument."
        // A good convension is to place a random number after the instrument name, to avoid conflicts with other instruments that might have the same name.
        this.instrumentId = "instrumentbase-302571"; // This should be *hardcoded*, so that we can identify the type of instrument when loading a project, even if the class definition is missing or has changed.
        this.currentChannel = 0;
        this.container = null; // This is used when tearDown() is called, to remove the generated HTML from the DOM. You can also use this in play() if you need to access the container for some reason.
    }

    /**
     * !!! CALL SUPER() IF YOU OVERRIDE THIS METHOD IN THE CHILD CLASS, OR YOU MIGHT CAUSE BUGS !!!
     * Callback for when the channel of the instrument is updated.
     * This will be called *for the first time* after init() and before play(). (And, of course, whenever the user changes the channel)
     * This is useful, for example, to update the UI of the instrument to reflect the current channel.
     * @param {number} channel The channelId
     */
    updateChannel(channel) {
        this.currentChannel = channel;
    }

    /**
     * Initialize the instrument. Here, you will do any resource-heavy stuff, like fetching files, ...
     */
    async init() {
        if (this.instrumentId === this.DEFAULT_INSTRUMENT_NAME) {
            throw new Error("You must change the instrumentId property in the constructor to a unique value [InstrumentBase]");
        }
        throw new Error("init() method not implemented [InstrumentBase]");
    }

    /**
     * !! PLEASE CALL THE SUPER() !!
     * Here you would generate the HTML for the instrument's UI
     * This can be used if you don't want to make a View, but rather just simple settings that can be changed in the instrument itself. For example, a simple audio file player instrument could have a "file input" element generated here.
     * @param {HTMLElement} htmlElement The container
     */
    genHtml(htmlElement) {
        if (this.container) {
            this.container.innerHTML = ""; // Clear the container before generating the new HTML
            this.tearUIDown();
        }
        this.container = htmlElement;
        if (!this.hasUI) {
            this.container.innerHTML = `<p>No settings available for this instrument.</p>`;
        }
    }

    /**
     * !!! element.on* is recommended for event handling in the generated HTML, instead of addEventListener, so you don't need to do anything in tearUIDown !!!
     * Same as genHtml, but for registering events on the generated HTML. Idfk why I made this separate from genHtml.
     */
    registerEvents() {
    }

    /**
     * Tear down the instrument's UI. This will be called when the instrument is unloaded.
     * Here you would cancel the events
     * THE HTML IS ALREADY REMOVED FROM THE DOM WHEN THIS IS CALLED
     */
    tearUIDown() { }

    /**
     * This will be called whenever an event is triggered that should make the instrument play a sound.
     * Examples:
     * - A piano roll event triggers a note to be played, with a certain velocity and duration
     * - The song is playing and reaches a point where an audio file should be played, so the instrument should play that audio file (if it's an "Audio file player", of course)
     * @param {object} parameters An object containing any parameters needed to play the sound. This is typically generated by a View. Here's some examples of default view-generated parameters:
     * - Piano roll note event: { type: "note", note: 60, velocity: 100, duration: 500 }
     */
    async play(parameters) {
        throw new Error("play() method not implemented [InstrumentBase]");
    }

    /**
     * Tear down the instrument. This will be called when the instrument is unloaded.
     */
    async tearDown() {
        if (this.container) {
            this.container.innerHTML = ""; // Remove the generated HTML from the DOM
        }
        this.tearUIDown();
    }

    /**
     * This is used when saving/loading a project to store the current state of the instrument parameters.
     * @returns {object} A Key-Val dict
     */
    saveParameters() {
        // Subclasses can override this method to return an object representing the current state of the instrument parameters for saving.
        return {};
    }

    /**
     * This is used when saving/loading a project to restore the state of the instrument parameters.
     * @param {object} params Params returned by saveParameters
     */
    loadParameters(params) {
        // Subclasses can override this method to load the instrument parameters from a saved state object.
    }
}