import ViewsIndex from "./ViewsIndex.js";

export class WindowManager {
    constructor(winContainer) {
        this.winContainer = winContainer;
    }

    openWindow(title, contentElement, disableClose = false) {
        let forceClose = false;
        const win = new WinBox(title, {
            root: this.winContainer,
            mount: contentElement,
            onclose: (force) => {
                if (!forceClose) {
                    win.window.style.display = "none"; // Hide the window, but don't destroy it, so we can reuse it later if needed.
                    return true; // Prevent the window from being destroyed
                }
            }
        });
        if (!disableClose) {
            const newControl = document.createElement("span");
            newControl.classList.add("wb-close");
            newControl.style.filter = "brightness(0) saturate(100%) invert(30%) sepia(98%) saturate(6956%) hue-rotate(355deg) brightness(92%) contrast(120%)"; // Generated by: https://angel-rs.github.io/css-color-filter-generator/
            win.window.querySelector(".wb-header>.wb-control").appendChild(newControl);
            newControl.addEventListener("click", async () => {
                if (await window.confirmDialog("Are you sure you want to close this window?", "Foce-Closing the window will unload the view, and you might lose unsaved progress. Normal closing is recommended.") === true) {
                    forceClose = true;
                    window.webDaw.app__unregisterView(title);
                    win.close(true);
                }
            });
        }
        return win;
    }

    openVMView(viewName) {
        const alreadyOpenView = window.webDaw.openedViews[viewName];
        if (alreadyOpenView) {
            alreadyOpenView.element.style.display = "block"; // Show the window if it's already open
            alreadyOpenView.element.winbox.focus(); // Focus the window
            return;
        }
        const viewClass = ViewsIndex[viewName];
        if (!viewClass.canBeOpened()) {
            window.error(false, `View ${viewName} cannot be opened right now.`);
            return;
        }
        if (!viewClass) {
            window.error(false, `View ${viewName} not found`);
            return;
        }
        const viewElement = document.createElement("div");
        const view = new viewClass();
        viewElement.addEventListener("mousedown", () => {
            window.webDaw.currentView = view;
        });
        window.webDaw.currentView = view; // Focused when opened
        view.genHtml(viewElement);
        view.registerEvents();
        const win = this.openWindow(viewName, viewElement);
        window.webDaw.app__registerView(viewName, view, win);
    }
}